-- Up Migration

-- 004_full_signal_set: generated from @ev/core's column catalogue by
-- scripts/generate-migration.mjs. Regenerating it is not how it is maintained —
-- see that script's header — and a later catalogue entry arrives as a later
-- migration, never as an edit to this one.
--
-- 187 columns: one per catalogued signal `sample` does not have yet.
-- Measured on a populated partitioned parent, ADD COLUMN is a catalogue write
-- rather than a table rewrite, so this is milliseconds even against real data,
-- and a null column costs a bit in the row header rather than a byte on disk.
-- One ALTER TABLE rather than 187, so the parent and each of its
-- partitions are locked once.
ALTER TABLE sample
  ADD COLUMN drive_rail                                    TEXT,
  ADD COLUMN bms_fullchargecomplete                        BOOLEAN,
  ADD COLUMN pack_voltage                                  REAL,
  ADD COLUMN pack_current                                  REAL,
  ADD COLUMN dcdc_enable                                   BOOLEAN,
  ADD COLUMN gear                                          TEXT,
  ADD COLUMN isolation_resistance                          REAL,
  ADD COLUMN pedal_position                                REAL,
  ADD COLUMN brake_pedal                                   TEXT,
  ADD COLUMN di_state_r                                    TEXT,
  ADD COLUMN di_heatsink_tr                                REAL,
  ADD COLUMN di_axle_speed_r                               REAL,
  ADD COLUMN di_torquemotor                                REAL,
  ADD COLUMN di_stator_temp_r                              REAL,
  ADD COLUMN di_v_bat_r                                    REAL,
  ADD COLUMN di_motor_current_r                            REAL,
  ADD COLUMN gps_state                                     TEXT,
  ADD COLUMN gps_heading                                   REAL,
  ADD COLUMN num_brick_voltage_max                         INT,
  ADD COLUMN brick_voltage_max                             REAL,
  ADD COLUMN num_brick_voltage_min                         INT,
  ADD COLUMN brick_voltage_min                             REAL,
  ADD COLUMN num_module_temp_max                           INT,
  ADD COLUMN module_temp_max                               REAL,
  ADD COLUMN num_module_temp_min                           INT,
  ADD COLUMN module_temp_min                               REAL,
  ADD COLUMN hvil                                          TEXT,
  ADD COLUMN charge_limit_soc                              REAL,
  ADD COLUMN fast_charger_present                          BOOLEAN,
  ADD COLUMN est_battery_range_km                          REAL,
  ADD COLUMN ideal_battery_range_km                        REAL,
  ADD COLUMN battery_level                                 REAL,
  ADD COLUMN time_to_full_charge_hours                     REAL,
  ADD COLUMN scheduled_charging_start_time                 TEXT,
  ADD COLUMN scheduled_charging_pending                    BOOLEAN,
  ADD COLUMN scheduled_departure_time                      TEXT,
  ADD COLUMN preconditioning_enabled                       BOOLEAN,
  ADD COLUMN scheduled_charging_mode                       TEXT,
  ADD COLUMN charge_amps                                   REAL,
  ADD COLUMN charge_enable_request                         BOOLEAN,
  ADD COLUMN charger_phases                                INT,
  ADD COLUMN charge_port_cold_weather_mode                 BOOLEAN,
  ADD COLUMN charge_current_request                        REAL,
  ADD COLUMN charge_current_request_max                    REAL,
  ADD COLUMN battery_heater_on                             BOOLEAN,
  ADD COLUMN not_enough_power_to_heat                      BOOLEAN,
  ADD COLUMN supercharger_session_trip_planner             BOOLEAN,
  ADD COLUMN fd_window                                     TEXT,
  ADD COLUMN fp_window                                     TEXT,
  ADD COLUMN rd_window                                     TEXT,
  ADD COLUMN rp_window                                     TEXT,
  ADD COLUMN vehicle_name                                  TEXT,
  ADD COLUMN sentry_mode                                   TEXT,
  ADD COLUMN speed_limit_mode                              BOOLEAN,
  ADD COLUMN current_limit_kph                             REAL,
  ADD COLUMN version                                       TEXT,
  ADD COLUMN tpms_last_seen_pressure_time_fl               TEXT,
  ADD COLUMN tpms_last_seen_pressure_time_fr               TEXT,
  ADD COLUMN tpms_last_seen_pressure_time_rl               TEXT,
  ADD COLUMN tpms_last_seen_pressure_time_rr               TEXT,
  ADD COLUMN seat_heater_left                              INT,
  ADD COLUMN seat_heater_right                             INT,
  ADD COLUMN seat_heater_rear_left                         INT,
  ADD COLUMN seat_heater_rear_right                        INT,
  ADD COLUMN seat_heater_rear_center                       INT,
  ADD COLUMN auto_seat_climate_left                        BOOLEAN,
  ADD COLUMN auto_seat_climate_right                       BOOLEAN,
  ADD COLUMN driver_seat_belt                              TEXT,
  ADD COLUMN passenger_seat_belt                           TEXT,
  ADD COLUMN driver_seat_occupied                          BOOLEAN,
  ADD COLUMN lateral_acceleration                          REAL,
  ADD COLUMN longitudinal_acceleration                     REAL,
  ADD COLUMN cruise_set_speed_kph                          REAL,
  ADD COLUMN lifetime_energy_used                          DOUBLE PRECISION,
  ADD COLUMN lifetime_energy_used_drive                    DOUBLE PRECISION,
  ADD COLUMN brake_pedal_pos                               REAL,
  ADD COLUMN route_last_updated                            TEXT,
  ADD COLUMN route_line                                    TEXT,
  ADD COLUMN km_to_arrival                                 REAL,
  ADD COLUMN minutes_to_arrival                            REAL,
  ADD COLUMN origin_location_lat                           DOUBLE PRECISION,
  ADD COLUMN origin_location_lon                           DOUBLE PRECISION,
  ADD COLUMN destination_location_lat                      DOUBLE PRECISION,
  ADD COLUMN destination_location_lon                      DOUBLE PRECISION,
  ADD COLUMN car_type                                      TEXT,
  ADD COLUMN trim                                          TEXT,
  ADD COLUMN exterior_color                                TEXT,
  ADD COLUMN roof_color                                    TEXT,
  ADD COLUMN charge_port                                   TEXT,
  ADD COLUMN charge_port_latch                             TEXT,
  ADD COLUMN guest_mode_enabled                            BOOLEAN,
  ADD COLUMN pin_to_drive_enabled                          BOOLEAN,
  ADD COLUMN paired_phone_key_and_key_fob_qty              INT,
  ADD COLUMN cruise_follow_distance                        TEXT,
  ADD COLUMN automatic_blind_spot_camera                   BOOLEAN,
  ADD COLUMN blind_spot_collision_warning_chime            BOOLEAN,
  ADD COLUMN speed_limit_warning                           TEXT,
  ADD COLUMN forward_collision_warning                     TEXT,
  ADD COLUMN lane_departure_avoidance                      TEXT,
  ADD COLUMN emergency_lane_departure_avoidance            BOOLEAN,
  ADD COLUMN automatic_emergency_braking_off               BOOLEAN,
  ADD COLUMN lifetime_energy_gained_regen                  DOUBLE PRECISION,
  ADD COLUMN di_state_f                                    TEXT,
  ADD COLUMN di_heatsink_tf                                REAL,
  ADD COLUMN di_axle_speed_f                               REAL,
  ADD COLUMN di_slave_torque_cmd                           REAL,
  ADD COLUMN di_torque_actual_r                            REAL,
  ADD COLUMN di_torque_actual_f                            REAL,
  ADD COLUMN di_stator_temp_f                              REAL,
  ADD COLUMN di_v_bat_f                                    REAL,
  ADD COLUMN di_motor_current_f                            REAL,
  ADD COLUMN energy_remaining                              REAL,
  ADD COLUMN service_mode                                  BOOLEAN,
  ADD COLUMN bms_state                                     TEXT,
  ADD COLUMN guest_mode_mobile_access_state                TEXT,
  ADD COLUMN destination_name                              TEXT,
  ADD COLUMN di_inverter_tr                                REAL,
  ADD COLUMN di_inverter_tf                                REAL,
  ADD COLUMN cabin_overheat_protection_mode                TEXT,
  ADD COLUMN cabin_overheat_protection_temperature_limit   TEXT,
  ADD COLUMN center_display                                TEXT,
  ADD COLUMN charge_port_door_open                         BOOLEAN,
  ADD COLUMN charger_voltage                               REAL,
  ADD COLUMN charging_cable_type                           TEXT,
  ADD COLUMN climate_keeper_mode                           TEXT,
  ADD COLUMN defrost_for_preconditioning                   BOOLEAN,
  ADD COLUMN defrost_mode                                  TEXT,
  ADD COLUMN efficiency_package                            TEXT,
  ADD COLUMN estimated_hours_to_charge_termination         REAL,
  ADD COLUMN europe_vehicle                                BOOLEAN,
  ADD COLUMN expected_energy_percent_at_trip_arrival       REAL,
  ADD COLUMN fast_charger_type                             TEXT,
  ADD COLUMN homelink_device_count                         INT,
  ADD COLUMN homelink_nearby                               BOOLEAN,
  ADD COLUMN hvac_ac_enabled                               BOOLEAN,
  ADD COLUMN hvac_auto_mode                                TEXT,
  ADD COLUMN hvac_fan_speed                                INT,
  ADD COLUMN hvac_fan_status                               TEXT,
  ADD COLUMN hvac_left_temperature_request                 REAL,
  ADD COLUMN hvac_power                                    TEXT,
  ADD COLUMN hvac_right_temperature_request                REAL,
  ADD COLUMN hvac_steering_wheel_heat_auto                 BOOLEAN,
  ADD COLUMN hvac_steering_wheel_heat_level                INT,
  ADD COLUMN rear_display_hvac_enabled                     BOOLEAN,
  ADD COLUMN rear_seat_heaters                             TEXT,
  ADD COLUMN remote_start_enabled                          BOOLEAN,
  ADD COLUMN right_hand_drive                              BOOLEAN,
  ADD COLUMN route_traffic_minutes_delay                   REAL,
  ADD COLUMN software_update_download_percent_complete     REAL,
  ADD COLUMN software_update_expected_duration_minutes     REAL,
  ADD COLUMN software_update_installation_percent_complete REAL,
  ADD COLUMN software_update_scheduled_start_time          TEXT,
  ADD COLUMN software_update_version                       TEXT,
  ADD COLUMN tpms_hard_warnings                            TEXT,
  ADD COLUMN tpms_soft_warnings                            TEXT,
  ADD COLUMN valet_mode_enabled                            BOOLEAN,
  ADD COLUMN wheel_type                                    TEXT,
  ADD COLUMN wiper_heat_enabled                            BOOLEAN,
  ADD COLUMN located_at_home                               BOOLEAN,
  ADD COLUMN located_at_work                               BOOLEAN,
  ADD COLUMN located_at_favorite                           BOOLEAN,
  ADD COLUMN setting_distance_unit                         TEXT,
  ADD COLUMN setting_temperature_unit                      TEXT,
  ADD COLUMN setting_24_hour_time                          BOOLEAN,
  ADD COLUMN setting_tire_pressure_unit                    TEXT,
  ADD COLUMN setting_charge_unit                           TEXT,
  ADD COLUMN climate_seat_cooling_front_left               INT,
  ADD COLUMN climate_seat_cooling_front_right              INT,
  ADD COLUMN lights_hazards_active                         BOOLEAN,
  ADD COLUMN lights_turn_signal                            TEXT,
  ADD COLUMN lights_high_beams                             BOOLEAN,
  ADD COLUMN sunroof_installed                             TEXT,
  ADD COLUMN seat_vent_enabled                             BOOLEAN,
  ADD COLUMN rear_defrost_enabled                          BOOLEAN,
  ADD COLUMN charge_rate_km_per_hour                       REAL,
  ADD COLUMN km_since_reset                                DOUBLE PRECISION,
  ADD COLUMN self_driving_km_since_reset                   DOUBLE PRECISION,
  ADD COLUMN gps_accuracy_meters                           REAL,
  ADD COLUMN lifetime_energy_charged_kwh                   DOUBLE PRECISION,
  ADD COLUMN brick_soc_min_percent                         REAL,
  ADD COLUMN nominal_full_pack_energy_kwh                  REAL,
  ADD COLUMN grade_estimate_percent                        REAL,
  ADD COLUMN max_speed_to_reach_destination_kph            REAL,
  ADD COLUMN software_update_available                     BOOLEAN,
  ADD COLUMN software_update_in_progress                   BOOLEAN,
  ADD COLUMN remote_start_active                           BOOLEAN,
  ADD COLUMN semi_cruise_speed_limit_kph                   REAL;

-- Down Migration

-- Dropping a column does NOT reclaim its slot: Postgres allows 1600 columns per
-- table counting dropped ones, so a down-then-up cycle spends 187 of the
-- remaining headroom. Fine once, worth knowing before doing it in a loop.
ALTER TABLE sample
  DROP COLUMN drive_rail,
  DROP COLUMN bms_fullchargecomplete,
  DROP COLUMN pack_voltage,
  DROP COLUMN pack_current,
  DROP COLUMN dcdc_enable,
  DROP COLUMN gear,
  DROP COLUMN isolation_resistance,
  DROP COLUMN pedal_position,
  DROP COLUMN brake_pedal,
  DROP COLUMN di_state_r,
  DROP COLUMN di_heatsink_tr,
  DROP COLUMN di_axle_speed_r,
  DROP COLUMN di_torquemotor,
  DROP COLUMN di_stator_temp_r,
  DROP COLUMN di_v_bat_r,
  DROP COLUMN di_motor_current_r,
  DROP COLUMN gps_state,
  DROP COLUMN gps_heading,
  DROP COLUMN num_brick_voltage_max,
  DROP COLUMN brick_voltage_max,
  DROP COLUMN num_brick_voltage_min,
  DROP COLUMN brick_voltage_min,
  DROP COLUMN num_module_temp_max,
  DROP COLUMN module_temp_max,
  DROP COLUMN num_module_temp_min,
  DROP COLUMN module_temp_min,
  DROP COLUMN hvil,
  DROP COLUMN charge_limit_soc,
  DROP COLUMN fast_charger_present,
  DROP COLUMN est_battery_range_km,
  DROP COLUMN ideal_battery_range_km,
  DROP COLUMN battery_level,
  DROP COLUMN time_to_full_charge_hours,
  DROP COLUMN scheduled_charging_start_time,
  DROP COLUMN scheduled_charging_pending,
  DROP COLUMN scheduled_departure_time,
  DROP COLUMN preconditioning_enabled,
  DROP COLUMN scheduled_charging_mode,
  DROP COLUMN charge_amps,
  DROP COLUMN charge_enable_request,
  DROP COLUMN charger_phases,
  DROP COLUMN charge_port_cold_weather_mode,
  DROP COLUMN charge_current_request,
  DROP COLUMN charge_current_request_max,
  DROP COLUMN battery_heater_on,
  DROP COLUMN not_enough_power_to_heat,
  DROP COLUMN supercharger_session_trip_planner,
  DROP COLUMN fd_window,
  DROP COLUMN fp_window,
  DROP COLUMN rd_window,
  DROP COLUMN rp_window,
  DROP COLUMN vehicle_name,
  DROP COLUMN sentry_mode,
  DROP COLUMN speed_limit_mode,
  DROP COLUMN current_limit_kph,
  DROP COLUMN version,
  DROP COLUMN tpms_last_seen_pressure_time_fl,
  DROP COLUMN tpms_last_seen_pressure_time_fr,
  DROP COLUMN tpms_last_seen_pressure_time_rl,
  DROP COLUMN tpms_last_seen_pressure_time_rr,
  DROP COLUMN seat_heater_left,
  DROP COLUMN seat_heater_right,
  DROP COLUMN seat_heater_rear_left,
  DROP COLUMN seat_heater_rear_right,
  DROP COLUMN seat_heater_rear_center,
  DROP COLUMN auto_seat_climate_left,
  DROP COLUMN auto_seat_climate_right,
  DROP COLUMN driver_seat_belt,
  DROP COLUMN passenger_seat_belt,
  DROP COLUMN driver_seat_occupied,
  DROP COLUMN lateral_acceleration,
  DROP COLUMN longitudinal_acceleration,
  DROP COLUMN cruise_set_speed_kph,
  DROP COLUMN lifetime_energy_used,
  DROP COLUMN lifetime_energy_used_drive,
  DROP COLUMN brake_pedal_pos,
  DROP COLUMN route_last_updated,
  DROP COLUMN route_line,
  DROP COLUMN km_to_arrival,
  DROP COLUMN minutes_to_arrival,
  DROP COLUMN origin_location_lat,
  DROP COLUMN origin_location_lon,
  DROP COLUMN destination_location_lat,
  DROP COLUMN destination_location_lon,
  DROP COLUMN car_type,
  DROP COLUMN trim,
  DROP COLUMN exterior_color,
  DROP COLUMN roof_color,
  DROP COLUMN charge_port,
  DROP COLUMN charge_port_latch,
  DROP COLUMN guest_mode_enabled,
  DROP COLUMN pin_to_drive_enabled,
  DROP COLUMN paired_phone_key_and_key_fob_qty,
  DROP COLUMN cruise_follow_distance,
  DROP COLUMN automatic_blind_spot_camera,
  DROP COLUMN blind_spot_collision_warning_chime,
  DROP COLUMN speed_limit_warning,
  DROP COLUMN forward_collision_warning,
  DROP COLUMN lane_departure_avoidance,
  DROP COLUMN emergency_lane_departure_avoidance,
  DROP COLUMN automatic_emergency_braking_off,
  DROP COLUMN lifetime_energy_gained_regen,
  DROP COLUMN di_state_f,
  DROP COLUMN di_heatsink_tf,
  DROP COLUMN di_axle_speed_f,
  DROP COLUMN di_slave_torque_cmd,
  DROP COLUMN di_torque_actual_r,
  DROP COLUMN di_torque_actual_f,
  DROP COLUMN di_stator_temp_f,
  DROP COLUMN di_v_bat_f,
  DROP COLUMN di_motor_current_f,
  DROP COLUMN energy_remaining,
  DROP COLUMN service_mode,
  DROP COLUMN bms_state,
  DROP COLUMN guest_mode_mobile_access_state,
  DROP COLUMN destination_name,
  DROP COLUMN di_inverter_tr,
  DROP COLUMN di_inverter_tf,
  DROP COLUMN cabin_overheat_protection_mode,
  DROP COLUMN cabin_overheat_protection_temperature_limit,
  DROP COLUMN center_display,
  DROP COLUMN charge_port_door_open,
  DROP COLUMN charger_voltage,
  DROP COLUMN charging_cable_type,
  DROP COLUMN climate_keeper_mode,
  DROP COLUMN defrost_for_preconditioning,
  DROP COLUMN defrost_mode,
  DROP COLUMN efficiency_package,
  DROP COLUMN estimated_hours_to_charge_termination,
  DROP COLUMN europe_vehicle,
  DROP COLUMN expected_energy_percent_at_trip_arrival,
  DROP COLUMN fast_charger_type,
  DROP COLUMN homelink_device_count,
  DROP COLUMN homelink_nearby,
  DROP COLUMN hvac_ac_enabled,
  DROP COLUMN hvac_auto_mode,
  DROP COLUMN hvac_fan_speed,
  DROP COLUMN hvac_fan_status,
  DROP COLUMN hvac_left_temperature_request,
  DROP COLUMN hvac_power,
  DROP COLUMN hvac_right_temperature_request,
  DROP COLUMN hvac_steering_wheel_heat_auto,
  DROP COLUMN hvac_steering_wheel_heat_level,
  DROP COLUMN rear_display_hvac_enabled,
  DROP COLUMN rear_seat_heaters,
  DROP COLUMN remote_start_enabled,
  DROP COLUMN right_hand_drive,
  DROP COLUMN route_traffic_minutes_delay,
  DROP COLUMN software_update_download_percent_complete,
  DROP COLUMN software_update_expected_duration_minutes,
  DROP COLUMN software_update_installation_percent_complete,
  DROP COLUMN software_update_scheduled_start_time,
  DROP COLUMN software_update_version,
  DROP COLUMN tpms_hard_warnings,
  DROP COLUMN tpms_soft_warnings,
  DROP COLUMN valet_mode_enabled,
  DROP COLUMN wheel_type,
  DROP COLUMN wiper_heat_enabled,
  DROP COLUMN located_at_home,
  DROP COLUMN located_at_work,
  DROP COLUMN located_at_favorite,
  DROP COLUMN setting_distance_unit,
  DROP COLUMN setting_temperature_unit,
  DROP COLUMN setting_24_hour_time,
  DROP COLUMN setting_tire_pressure_unit,
  DROP COLUMN setting_charge_unit,
  DROP COLUMN climate_seat_cooling_front_left,
  DROP COLUMN climate_seat_cooling_front_right,
  DROP COLUMN lights_hazards_active,
  DROP COLUMN lights_turn_signal,
  DROP COLUMN lights_high_beams,
  DROP COLUMN sunroof_installed,
  DROP COLUMN seat_vent_enabled,
  DROP COLUMN rear_defrost_enabled,
  DROP COLUMN charge_rate_km_per_hour,
  DROP COLUMN km_since_reset,
  DROP COLUMN self_driving_km_since_reset,
  DROP COLUMN gps_accuracy_meters,
  DROP COLUMN lifetime_energy_charged_kwh,
  DROP COLUMN brick_soc_min_percent,
  DROP COLUMN nominal_full_pack_energy_kwh,
  DROP COLUMN grade_estimate_percent,
  DROP COLUMN max_speed_to_reach_destination_kph,
  DROP COLUMN software_update_available,
  DROP COLUMN software_update_in_progress,
  DROP COLUMN remote_start_active,
  DROP COLUMN semi_cruise_speed_limit_kph;
